# Análisis Exploratorio de Datos: EDA - Parte 1
En el proceso de análisis exploratio de datos de este proyecto se llevará a cabo en esta primera parte desde la extracción, transformación y carga de los datos, esto con el objetivo de contar con datos de calidad para el análisis exploratorio posterior. 

En esta fase se verán procesos de limpieza y transformación de datos; descripción y análisis de lo que se va obteniendo de los datos limpios y la realización de gráficas que permitan visualizar el comportamiento de los datos con las respectivas conclusiones y análisis de estas. 

### Importanciones


In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
from summarytools import dfSummary
import warnings
warnings.filterwarnings('ignore')


In [2]:
dfHechos = pd.read_excel('homicidios.xlsx', sheet_name="HECHOS")
dfVictimas = pd.read_excel('homicidios.xlsx', sheet_name="VICTIMAS")

### **HECHOS**

In [3]:
dfHechos

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0    2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1    2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2    2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   
3    2016-0004           1 2016-01-10  2016   1  10  00:00:00   0   
4    2016-0005           1 2016-01-21  2016   1  21  05:20:00   5   
..         ...         ...        ...   ...  ..  ..       ...  ..   
691  2021-0093           1 2021-12-13  2021  12  13  17:10:00  17   
692  2021-0094           1 2021-12-20  2021  12  20  01:10:00   1   
693  2021-0095           1 2021-12-30  2021  12  30  00:43:00   0   
694  2021-0096           1 2021-12-15  2021  12  15  10:30:00  10   
695  2021-0097           1 2021-11-18  2021  11  18  06:10:00   6   

                               LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  Altura  \
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...     NaN   
1            AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...     NaN   
2                           AV ENTRE RIOS 2034       AVENIDA  ...  2034.0   
3        AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...     NaN   
4    AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...     NaN   
..                                         ...           ...  ...     ...   
691                          AV. RIESTRA Y MOM       AVENIDA  ...     NaN   
692                    AU DELLEPIANE Y LACARRA     AUTOPISTA  ...     NaN   
693                        AV. GAONA Y TERRADA       AVENIDA  ...     NaN   
694                         AV. EVA PERON 4071       AVENIDA  ...  4071.0   
695                    PADRE CARLOS MUJICA 709         CALLE  ...   709.0   

                                   Cruce  \
0    FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                    DE LOS CORRALES AV.   
2                                    NaN   
3               VILLEGAS, CONRADO, GRAL.   
4                SAENZ PE?A, LUIS, PRES.   
..                                   ...   
691                                  MOM   
692                          LACARRA AV.   
693                              TERRADA   
694                                  NaN   
695                                  NaN   

                                 Dirección Normalizada COMUNA  \
0    PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1                 PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                  ENTRE RIOS AV. 2034      1   
3            LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4              SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   
..                                                 ...    ...   
691                                  RIESTRA AV. y MOM      7   
692         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.      9   
693                                GAONA AV. y TERRADA     11   
694                                PERON, EVA AV. 4071      9   
695                            PADRE CARLOS MUGICA 709      1   

                                   XY (CABA)         pos x         pos y  \
0      Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1      Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2     Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3      Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4    Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   
..                                       ...           ...           ...   
691   Point (102728.60090138 98186.24929177)  -58.43353773  -34.64561636   
692    Point (99624.29795829 97569.69801131)  -58.46739825  -34.65117757   
693   Point (99116.45492358 101045.23284826)  -58.47293407  -34.61984745   
694    Point (99324.54463985 97676.26932409)  -58.47066794  -34.65021673   
695  Point (107664.16647795 104708.63962087)  -58.37976155  -34.58679619   

      PARTICIPANTES    VICTIMA    A

In [4]:
dfHechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Altura                 129 non-null    float64       
 12  Cruce                  525 non-null    object        
 13  Direc

In [5]:
dfHechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

A partir de esta información obtenida, se observa que el dataframe de la tabla 'HECHOS' tiene 696 filas x 21 columnas las cuales tienen nombres que no están normalizados, así que se procede a **normalizar los nombres de las columnas**.

In [6]:
# Cambiamos el nombre a minúsculas
dfHechos.columns = [x.lower() for x in dfHechos.columns]
# Se reemplazan los guiones por espacios
dfHechos.columns = dfHechos.columns.str.replace('_', ' ')
# Se renombran algunas columnas
dfHechos = dfHechos.rename(columns={'nro_victimas': 'n víctimas',
                                                      'aaaa':'año',
                                                      'mm':'mes',
                                                      'dd':'día',
                                                      'hh':'hora entera',
                                                      'id': 'id hecho'})
dfHechos.columns



Index(['id hecho', 'n victimas', 'fecha', 'año', 'mes', 'día', 'hora',
       'hora entera', 'lugar del hecho', 'tipo de calle', 'calle', 'altura',
       'cruce', 'dirección normalizada', 'comuna', 'xy (caba)', 'pos x',
       'pos y', 'participantes', 'victima', 'acusado'],
      dtype='object')

## Revisión de Datos (Hechos)
### Datos Duplicados


In [7]:
dfHechos[dfHechos.duplicated()]

Empty DataFrame
Columns: [id hecho, n victimas, fecha, año, mes, día, hora, hora entera, lugar del hecho, tipo de calle, calle, altura, cruce, dirección normalizada, comuna, xy (caba), pos x, pos y, participantes, victima, acusado]
Index: []

[0 rows x 21 columns]

Se puede ver que no hay filas con datos duplicados. Asi que ahora veremos los:

### Datos Nulos

In [8]:
dfHechos.isnull().sum()

id hecho                   0
n victimas                 0
fecha                      0
año                        0
mes                        0
día                        0
hora                       0
hora entera                0
lugar del hecho            0
tipo de calle              0
calle                      1
altura                   567
cruce                    171
dirección normalizada      8
comuna                     0
xy (caba)                  0
pos x                      0
pos y                      0
participantes              0
victima                    0
acusado                    0
dtype: int64

Para saber el porcentaje de datos nulos con exactitud, se crea la siguiente función que explica mejor las métricas en datos nulos.

In [9]:
def DataType(df):
    dfDict = {
        "name": [], "data_type": [], "not_null_%": [], "null_%": [], "null": []
    }
    for column in df.columns:
        notNull = (df[column].count() / len(df)) * 100
        dfDict["name"].append(column)
        dfDict["data_type"].append(df[column].apply(type).unique())
        dfDict["not_null_%"].append(round(notNull, 2))
        dfDict["null_%"].append(round(100-notNull, 2))
        dfDict["null"].append(df[column].isnull().sum())
    dfDataType=pd.DataFrame(dfDict)
    return dfDataType

In [10]:
DataType(dfHechos)

name                                          data_type  \
0                id hecho                                    [<class 'str'>]   
1              n victimas                                    [<class 'int'>]   
2                   fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                     año                                    [<class 'int'>]   
4                     mes                                    [<class 'int'>]   
5                     día                                    [<class 'int'>]   
6                    hora  [<class 'datetime.time'>, <class 'str'>, <clas...   
7             hora entera                     [<class 'int'>, <class 'str'>]   
8         lugar del hecho                                    [<class 'str'>]   
9           tipo de calle                                    [<class 'str'>]   
10                  calle                   [<class 'str'>, <class 'float'>]   
11                 altura                                  [<class 'float'>]   
12                  cruce                   [<class 'str'>, <class 'float'>]   
13  dirección normalizada                   [<class 'str'>, <class 'float'>]   
14                 comuna                                    [<class 'int'>]   
15              xy (caba)                                    [<class 'str'>]   
16                  pos x                                    [<class 'str'>]   
17                  pos y                                    [<class 'str'>]   
18          participantes                                    [<class 'str'>]   
19                victima                                    [<class 'str'>]   
20                acusado                                    [<class 'str'>]   

    not_null_%  null_%  null  
0       100.00    0.00     0  
1       100.00    0.00     0  
2       100.00    0.00     0  
3       100.00    0.00     0  
4       100.00    0.00     0  
5       100.00    0.00     0  
6       100.00    0.00     0  
7       100.00    0.00     0  
8       100.00    0.00     0  
9       100.00    0.00     0  
10       99.86    0.14     1  
11       18.53   81.47   567  
12       75.43   24.57   171  
13       98.85    1.15     8  
14      100.00    0.00     0  
15      100.00    0.00     0  
16      100.00    0.00     0  
17      100.00    0.00     0  
18      100.00    0.00     0  
19      100.00    0.00     0  
20      100.00    0.00     0

Podemos ver que la mayoría de datos nulos provienen de las columnas 'altura' y 'cruce', aunque también hay datos nulos mínimos en las columnas 'dirección normalizada' y 'calle'.

Pero la gran mayoría de datos nulos están en la columna 'altura' la cual indica la altura de la arteria donde se produjo el hecho; así que esta información también está relacionada con la información de la columna 'calle' y con la de la columna de la dirección.

Así que la información de 'altura' no parece ser relevante para este análisis, entonces se contempla descartar esta columna del dataframe, así que hay que analizar sus aristas para tomar la decisión de eliminar esta columna. 
Para esto observamos las columnas dichas:

In [11]:
dfHechos[['altura', 'calle', 'dirección normalizada']][:10]

altura              calle  \
0     NaN   PIEDRA BUENA AV.   
1     NaN     PAZ, GRAL. AV.   
2  2034.0     ENTRE RIOS AV.   
3     NaN     LARRAZABAL AV.   
4     NaN       SAN JUAN AV.   
5     NaN  27 DE FEBRERO AV.   
6     NaN             NOGOYA   
7     NaN     PAZ, GRAL. AV.   
8     NaN       BELGRANO AV.   
9  1366.0     ENTRE RIOS AV.   

                               dirección normalizada  
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...  
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.  
2                                ENTRE RIOS AV. 2034  
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.  
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.  
5                   27 DE FEBRERO AV. y ESCALADA AV.  
6                      NOGOYA y GONZALEZ, JOAQUIN V.  
7               PAZ, GRAL. AV. y DE LOS CORRALES AV.  
8               BELGRANO AV. e IRIGOYEN, BERNARDO DE  
9                                ENTRE RIOS AV. 1366

Se puede ver que las filas que no tienen datos en altura, es porque el hecho ocurre en un cruce, así que vemos como se relacionan con la columna cruce:

In [12]:
dfHechos[['altura', 'calle', 'dirección normalizada', 'cruce']][:10]

altura              calle  \
0     NaN   PIEDRA BUENA AV.   
1     NaN     PAZ, GRAL. AV.   
2  2034.0     ENTRE RIOS AV.   
3     NaN     LARRAZABAL AV.   
4     NaN       SAN JUAN AV.   
5     NaN  27 DE FEBRERO AV.   
6     NaN             NOGOYA   
7     NaN     PAZ, GRAL. AV.   
8     NaN       BELGRANO AV.   
9  1366.0     ENTRE RIOS AV.   

                               dirección normalizada  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                ENTRE RIOS AV. 2034   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   
5                   27 DE FEBRERO AV. y ESCALADA AV.   
6                      NOGOYA y GONZALEZ, JOAQUIN V.   
7               PAZ, GRAL. AV. y DE LOS CORRALES AV.   
8               BELGRANO AV. e IRIGOYEN, BERNARDO DE   
9                                ENTRE RIOS AV. 1366   

                                 cruce  
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.  
1                  DE LOS CORRALES AV.  
2                                  NaN  
3             VILLEGAS, CONRADO, GRAL.  
4              SAENZ PE?A, LUIS, PRES.  
5                         ESCALADA AV.  
6                 GONZALEZ, JOAQUIN V.  
7                  DE LOS CORRALES AV.  
8                IRIGOYEN, BERNARDO DE  
9                                  NaN

Efectivamente vemos la relación que tienen, ya que si hay dato en 'altura', no lo hay en 'cruce' y viceversa, esto quiere decir que son mutuamente excluyentes; si un siniestro ocurre en el cruce no puede haber ocurrido en la altura de la calle y viceversa. 

Para estar más seguros de esto, verificamos que no hayan filas donde las dos columnas esten ocupadas simultaneamente. 

In [13]:
dfHechos[dfHechos[['altura', 'cruce']].notna().all(axis=1)]

Empty DataFrame
Columns: [id hecho, n victimas, fecha, año, mes, día, hora, hora entera, lugar del hecho, tipo de calle, calle, altura, cruce, dirección normalizada, comuna, xy (caba), pos x, pos y, participantes, victima, acusado]
Index: []

[0 rows x 21 columns]

Se puede ver que no hay filas donde hayan datos en estas dos columnas a la vez. Pero puede ocurrir que hayan datos nulos a la vez y se puede ver a continuación:

In [14]:
alturaycruceNull = dfHechos[
    # Se filtra el dataframe en los casos en los que 'altura' y 'cruce' son nulos a la vez
    dfHechos[['altura', 'cruce']].isnull().all(axis = 1)
]
alturaycruceNull.head()

id hecho  n victimas      fecha   año  mes  día      hora hora entera  \
35  2016-0049           1 2016-04-17  2016    4   17  00:00:00           0   
38  2016-0052           1 2016-04-20  2016    4   20  20:00:00          20   
64  2016-0087           1 2016-07-02  2016    7    3  00:10:00           0   
71  2016-0096           1 2016-07-25  2016    7   25  07:00:00           7   
81  2016-0107           1 2016-08-20  2016    8   20  08:22:00           8   

                                      lugar del hecho tipo de calle  ...  \
35  AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI KM....     AUTOPISTA  ...   
38                         AUTOPISTA LUGONES PK 10000     AUTOPISTA  ...   
64   AUTOPISTA 1 SUR PTE ARTURO FRONDIZI Y AV CASEROS     AUTOPISTA  ...   
71       AUTOPISTA DELLEPIANE LUIS TTE. GRAL. KM. 2,3     AUTOPISTA  ...   
81            AUTOPISTA 9 DE JULIO SUR ALT AV MENDOZA     AUTOPISTA  ...   

   altura  cruce                              dirección normalizada comuna  \
35    NaN    NaN         AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI      4   
38    NaN    NaN                                                NaN     13   
64    NaN    NaN  AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI y C...      1   
71    NaN    NaN               AUTOPISTA DELLEPIANE LUIS TTE. GRAL.      8   
81    NaN    NaN  AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI y D...      4   

                                  xy (caba)               pos x  \
35                              Point (. .)  -58.37714647568196   
38                              Point (. .)                   .   
64  Point (107762.62066736 100018.90176187)        -58.37864583   
71                              Point (. .)  -58.47433193007387   
81   Point (108408.31858686 97219.56218484)        -58.37157668   

                 pos y     participantes victima      acusado  
35  -34.63657525428238             SD-SD      SD           SD  
38                   .           MOTO-SD    MOTO           SD  
64        -34.62907067  MOTO-OBJETO FIJO    MOTO  OBJETO FIJO  
71  -34.66684950051973       MOTO-CARGAS    MOTO       CARGAS  
81        -34.65429986         MOTO-AUTO    MOTO         AUTO  

[5 rows x 21 columns]

Se puede ver que cuando no hay datos tanto en 'altura' como en 'cruce', el tipo de calle donde ocurrió el hecho es principalmente 'AUTOPISTA'. Para corroborar esto, se crea una función que nos arroje el porcentaje y la cantidad de los datos de la columna 'tipo de calle'.

In [15]:
def DataPorcentaje(df, column):
    counts = df[column].value_counts()
    percentages = round(100 * counts / len(df), 2)
    dfResults = pd.DataFrame({
        "Cantidad":counts,
        "Porcentaje":percentages
    })
    return dfResults

In [16]:
DataPorcentaje(alturaycruceNull, 'tipo de calle')

Cantidad  Porcentaje
tipo de calle                      
AUTOPISTA            39       92.86
CALLE                 2        4.76
GRAL PAZ              1        2.38

A partir de esta información se puede decir que cuando no hay datos tanto en 'altura' como en 'cruce', significa que la mayoría de los siniestros ocurrieron en la 'AUTOPISTA'. 

También se puede ver que hay los tipos de calle: 'CALLE' y 'GRAL PAZ', estos datos, pueden tomarse como outliers por diversos motivos. 

Así que a partir de la información obtenida, podemos confirmar que la columna 'altura' no es necesaria para este análisis, ya que podemos concluir su información a partir de otras columnas como 'cruce' y de ser necesario 'calle' y 'tipo de calle'. Entonces se procede a eliminar la columna altura del dataframe.

In [17]:
# Se elimina la columna 'altura' 
del dfHechos['altura']

In [18]:
dfHechos.columns

Index(['id hecho', 'n victimas', 'fecha', 'año', 'mes', 'día', 'hora',
       'hora entera', 'lugar del hecho', 'tipo de calle', 'calle', 'cruce',
       'dirección normalizada', 'comuna', 'xy (caba)', 'pos x', 'pos y',
       'participantes', 'victima', 'acusado'],
      dtype='object')

Para la columna 'cruce', la cual nos indica el nombre de los cruces en donde ocurrieron los siniestros (para los que ocurrieron en cruces), y en la cual hay 24,57% de valores faltantes, se decide transformar el tipo de dato de esta columna a booleano, para que nos indique solamente si el hecho fue en un cruce o no; ya que la información de esta columna también está en las de 'dirección normalizada' y 'lugar del hecho'.

Así que para efectos de simplificar la información para el análisis será True si fue en cruce o False si no lo fue. 

In [19]:
dfHechos['cruce'] = np.where(
    dfHechos['cruce'].notnull(),
    True,
    False)

In [20]:
dfHechos[['cruce', 'calle', 'dirección normalizada', 'lugar del hecho', 'tipo de calle']]

cruce                         calle  \
0     True              PIEDRA BUENA AV.   
1     True                PAZ, GRAL. AV.   
2    False                ENTRE RIOS AV.   
3     True                LARRAZABAL AV.   
4     True                  SAN JUAN AV.   
..     ...                           ...   
691   True                   RIESTRA AV.   
692   True  DELLEPIANE, LUIS, TTE. GRAL.   
693   True                     GAONA AV.   
694  False                PERON, EVA AV.   
695  False           PADRE CARLOS MUJICA   

                                 dirección normalizada  \
0    PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1                 PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                  ENTRE RIOS AV. 2034   
3            LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4              SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   
..                                                 ...   
691                                  RIESTRA AV. y MOM   
692         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.   
693                                GAONA AV. y TERRADA   
694                                PERON, EVA AV. 4071   
695                            PADRE CARLOS MUGICA 709   

                               lugar del hecho tipo de calle  
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  
1            AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  
2                           AV ENTRE RIOS 2034       AVENIDA  
3        AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  
4    AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  
..                                         ...           ...  
691                          AV. RIESTRA Y MOM       AVENIDA  
692                    AU DELLEPIANE Y LACARRA     AUTOPISTA  
693                        AV. GAONA Y TERRADA       AVENIDA  
694                         AV. EVA PERON 4071       AVENIDA  
695                    PADRE CARLOS MUJICA 709         CALLE  

[696 rows x 5 columns]

Seguidamente observamos la columna 'dirección normalizada', donde sus datos son nulos, los cuales son 8, que equivalen al 1.1% de los datos de esta columna. 

In [21]:
dfHechos[dfHechos['dirección normalizada'].isnull()][['dirección normalizada', 'lugar del hecho', 'tipo de calle']]

dirección normalizada                          lugar del hecho  \
38                    NaN               AUTOPISTA LUGONES PK 10000   
106                   NaN         AU BUENOS AIRES - LA PLATA KM. 4   
119                   NaN                                       SD   
180                   NaN  AU PERITO MORENO Y RAMAL ENLACE AU1/AU6   
181                   NaN                       AU DELLEPIANE 2400   
313                   NaN                 AUTOPISTA LUGONES KM 4.7   
546                   NaN             LUGONES, LEOPOLDO AV. KM 6,1   
621                   NaN         AU BUENOS AIRES LA PLATA  KM 4,5   

    tipo de calle  
38      AUTOPISTA  
106     AUTOPISTA  
119         CALLE  
180     AUTOPISTA  
181     AUTOPISTA  
313     AUTOPISTA  
546     AUTOPISTA  
621     AUTOPISTA

Para este caso no se considera eliminar los registros faltantes, entonces se cambian los datos nulos a 'SD' indicando que es un campo Sin Dato. 

In [22]:
dfHechos['dirección normalizada'].fillna('SD', inplace=True)
dfHechos[dfHechos['dirección normalizada'] == 'SD'][['dirección normalizada', 'lugar del hecho', 'tipo de calle']]

dirección normalizada                          lugar del hecho  \
38                     SD               AUTOPISTA LUGONES PK 10000   
106                    SD         AU BUENOS AIRES - LA PLATA KM. 4   
119                    SD                                       SD   
180                    SD  AU PERITO MORENO Y RAMAL ENLACE AU1/AU6   
181                    SD                       AU DELLEPIANE 2400   
313                    SD                 AUTOPISTA LUGONES KM 4.7   
546                    SD             LUGONES, LEOPOLDO AV. KM 6,1   
621                    SD         AU BUENOS AIRES LA PLATA  KM 4,5   

    tipo de calle  
38      AUTOPISTA  
106     AUTOPISTA  
119         CALLE  
180     AUTOPISTA  
181     AUTOPISTA  
313     AUTOPISTA  
546     AUTOPISTA  
621     AUTOPISTA

Para la columna 'calle', la cual tiene 1 dato nulo, se procede a imputar el dato nulo como 'SD' = Sin Dato. 

In [23]:
dfHechos['calle'] = dfHechos['calle'].fillna('SD')
dfHechos[dfHechos['calle'] == 'SD']

id hecho  n victimas      fecha   año  mes  día      hora hora entera  \
119  2016-0151           1 2016-11-18  2016   11   18  20:35:00          20   

    lugar del hecho tipo de calle calle  cruce dirección normalizada  comuna  \
119              SD         CALLE    SD  False                    SD       0   

       xy (caba) pos x pos y participantes victima acusado  
119  Point (. .)     .     .     PEATON-SD  PEATON      SD

Corroboramos el tipo de datos de nuestro dataframe con la función DataType, para ver si ya no tenemos datos nulos.

In [24]:
DataType(dfHechos)

name                                          data_type  \
0                id hecho                                    [<class 'str'>]   
1              n victimas                                    [<class 'int'>]   
2                   fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                     año                                    [<class 'int'>]   
4                     mes                                    [<class 'int'>]   
5                     día                                    [<class 'int'>]   
6                    hora  [<class 'datetime.time'>, <class 'str'>, <clas...   
7             hora entera                     [<class 'int'>, <class 'str'>]   
8         lugar del hecho                                    [<class 'str'>]   
9           tipo de calle                                    [<class 'str'>]   
10                  calle                                    [<class 'str'>]   
11                  cruce                                   [<class 'bool'>]   
12  dirección normalizada                                    [<class 'str'>]   
13                 comuna                                    [<class 'int'>]   
14              xy (caba)                                    [<class 'str'>]   
15                  pos x                                    [<class 'str'>]   
16                  pos y                                    [<class 'str'>]   
17          participantes                                    [<class 'str'>]   
18                victima                                    [<class 'str'>]   
19                acusado                                    [<class 'str'>]   

    not_null_%  null_%  null  
0        100.0     0.0     0  
1        100.0     0.0     0  
2        100.0     0.0     0  
3        100.0     0.0     0  
4        100.0     0.0     0  
5        100.0     0.0     0  
6        100.0     0.0     0  
7        100.0     0.0     0  
8        100.0     0.0     0  
9        100.0     0.0     0  
10       100.0     0.0     0  
11       100.0     0.0     0  
12       100.0     0.0     0  
13       100.0     0.0     0  
14       100.0     0.0     0  
15       100.0     0.0     0  
16       100.0     0.0     0  
17       100.0     0.0     0  
18       100.0     0.0     0  
19       100.0     0.0     0

### Tipos de Datos 
Se puede ver que las columnas de horas ('hora' y 'hora entera'), tienen tipos de datos diferentes, así que se procede a normalizar:

In [25]:
dfHechos['hora'].apply(type).value_counts()

hora
<class 'datetime.time'>        608
<class 'str'>                   85
<class 'datetime.datetime'>      3
Name: count, dtype: int64

Se procede a normalizar por el tipo 'datetime.time', ya que de este tipo son la mayoría de los datos.

In [26]:
# Filtramos los datos de la columna 'hora' que estan como str
dfHechos[dfHechos['hora'].apply(type) == str]['hora'].unique()

array(['22:50:00', '16:40:00', '10:12:00', '09:40:00', '22:30:00',
       '21:15:00', '02:30:00', '17:50:00', '10:30:00', '13:30:00',
       '08:15:00', '20:00:00', '01:00:00', '10:15:00', '04:15:00',
       '07:15:00', '12:30:00', '22:00:00', '10:45:00', '00:00:00',
       '06:00:00', '23:00:00', '04:45:00', '15:45:00', '18:00:00',
       '01:30:00', '13:00:00', '18:15:00', '16:45:00', '23:15:00',
       '06:30:00', '09:00:00', '07:00:00', '03:15:00', '18:45:00',
       '20:30:00', '11:15:00', '19:20:00', '17:56:00', '10:34:00',
       '08:20:00', '08:41:00', '05:35:00', '00:59:00', '22:20:00',
       '05:00:00', '14:25:00', '00:15:00', '00:30:00', '17:51:00',
       '18:12:00', '22:02:00', '14:20:00', '22:12:00', '03:05:00',
       '12:13:00', '09:18:00', '11:00:00', '02:15:00', '14:49:00',
       '13:34:00', '16:32:00', '03:32:00', '19:40:00', '21:12:00',
       '09:14:00', '04:30:00', '04:01:00', '03:00:00', '08:26:00',
       '14:07:00', '21:00:00', '15:42:00', '09:30:00', '05:25:

In [27]:
# Convertimos estos datos a formato time, excepto el SD
dfHechos['hora'] = pd.to_datetime(
    dfHechos['hora'],
    format = '%H:%M:%S', errors = 'coerce'
).dt.time.fillna('SD')

Ahora vemos los tipos de datos de la columna 'hora entera':

In [28]:
dfHechos['hora entera'].apply(type).value_counts()

hora entera
<class 'int'>    695
<class 'str'>      1
Name: count, dtype: int64

Corresponde al mismo tipo de dato imputado anteriormente, así que se mantiene de esa forma.

In [29]:
dfHechos[dfHechos['hora entera'].apply(type) == str]

id hecho  n victimas      fecha   año  mes  día hora hora entera  \
518  2019-0103           1 2019-12-18  2019   12   18   SD          SD   

             lugar del hecho tipo de calle           calle  cruce  \
518  PAZ, GRAL. AV. Y GRIVEO      GRAL PAZ  PAZ, GRAL. AV.   True   

       dirección normalizada  comuna                               xy (caba)  \
518  PAZ, GRAL. AV. y GRIVEO      11  Point (94643.11254058 103831.57115061)   

            pos x         pos y participantes victima acusado  
518  -58.52169422  -34.59471640     MOTO-MOTO    MOTO    MOTO

### Variables 
Hay 3 variables que se clasifican en categorías: 'tipo de calle', 'victima' y 'acusado'; así que verificaremos si los datos pertenecen a dichas categorias.

In [30]:
dfHechos['tipo de calle'].unique()

array(['AVENIDA', 'GRAL PAZ', 'CALLE', 'AUTOPISTA'], dtype=object)

In [31]:
dfHechos['victima'].unique()

array(['MOTO', 'AUTO', 'PEATON', 'SD', 'CARGAS', 'BICICLETA', 'PASAJEROS',
       'MOVIL', 'OBJETO FIJO', 'PEATON_MOTO'], dtype=object)

In [32]:
dfHechos['acusado'].unique()

array(['AUTO', 'PASAJEROS', 'SD', 'OBJETO FIJO', 'CARGAS', 'MOTO',
       'MULTIPLE', 'OTRO', 'BICICLETA', 'TREN'], dtype=object)

Para las columnas 'tipo de calle' y 'acusado' no se obersvan datos distintos a los esperados. En cambio para la columna 'victima' se observan los datos: 'OBJETO FIJO' y 'PEATON_MOTO', que no están en el diccionario del dataset. Entonces deben ser corregidas.

In [33]:
# Observamos las filas con las anomalías
dfHechos[dfHechos['victima'].isin(['OBJETO FIJO', 'PEATON_MOTO'])]

id hecho  n victimas      fecha   año  mes  día      hora hora entera  \
230  2017-0108           2 2017-09-02  2017    9    2  04:53:08           4   
583  2020-0063           2 2020-12-05  2020   12    5  07:10:00           7   

              lugar del hecho tipo de calle           calle  cruce  \
230   AV. GRAL. PAZ Y MACHAIN      GRAL PAZ  PAZ, GRAL. AV.   True   
583  NUEVA YORK Y ALTA GRACIA         CALLE      NUEVA YORK   True   

        dirección normalizada  comuna                               xy (caba)  \
230  PAZ, GRAL. AV. y MACHAIN      12  Point (97098.48468623 109019.96106626)   
583  NUEVA YORK y ALTA GRACIA      11  Point (94080.62190808 102083.62453795)   

            pos x         pos y     participantes      victima acusado  
230  -58.49491054  -34.54795581  AUTO-OBJETO FIJO  OBJETO FIJO    AUTO  
583  -58.52783814  -34.61047001  PEATON_MOTO-MOTO  PEATON_MOTO    MOTO

A partir del orden del dataset se puede inferir que en la fila del dato 'OBJETO FIJO' de la columna 'victima', están invertidos los valores de 'victima' y 'acusado', pues las demás filas tienen determinado orden; para verificar, veremos nuevamente el dataframe:

In [34]:
dfHechos[['id hecho', 'participantes', 'victima', 'acusado']]

id hecho   participantes    victima    acusado
0    2016-0001       MOTO-AUTO       MOTO       AUTO
1    2016-0002  AUTO-PASAJEROS       AUTO  PASAJEROS
2    2016-0003       MOTO-AUTO       MOTO       AUTO
3    2016-0004         MOTO-SD       MOTO         SD
4    2016-0005  MOTO-PASAJEROS       MOTO  PASAJEROS
..         ...             ...        ...        ...
691  2021-0093       MOTO-AUTO       MOTO       AUTO
692  2021-0094       MOTO-AUTO       MOTO       AUTO
693  2021-0095     MOTO-CARGAS       MOTO     CARGAS
694  2021-0096     AUTO-CARGAS       AUTO     CARGAS
695  2021-0097  BICICLETA-AUTO  BICICLETA       AUTO

[696 rows x 4 columns]

In [35]:
dfHechos.loc[
    dfHechos['id hecho'] == '2017-0108',
    ['victima', 'acusado']] = ['AUTO', 'OBJETO FIJO']
dfHechos[dfHechos['id hecho'] == '2017-0108']

id hecho  n victimas      fecha   año  mes  día      hora hora entera  \
230  2017-0108           2 2017-09-02  2017    9    2  04:53:08           4   

             lugar del hecho tipo de calle           calle  cruce  \
230  AV. GRAL. PAZ Y MACHAIN      GRAL PAZ  PAZ, GRAL. AV.   True   

        dirección normalizada  comuna                               xy (caba)  \
230  PAZ, GRAL. AV. y MACHAIN      12  Point (97098.48468623 109019.96106626)   

            pos x         pos y     participantes victima      acusado  
230  -58.49491054  -34.54795581  AUTO-OBJETO FIJO    AUTO  OBJETO FIJO

In [36]:
# Para la fila de 'PEATON_MOTO' imputaremos SD, ya que no hay como verificar que haya tenido otra causa este error.
dfHechos['victima'] = dfHechos['victima'].replace({'PEATON_MOTO': 'SD'})

In [37]:
# Verificamos los cambios para las dos filas:
dfHechos[dfHechos['id hecho'].isin(['2017-0108', '2020-0063'])]

id hecho  n victimas      fecha   año  mes  día      hora hora entera  \
230  2017-0108           2 2017-09-02  2017    9    2  04:53:08           4   
583  2020-0063           2 2020-12-05  2020   12    5  07:10:00           7   

              lugar del hecho tipo de calle           calle  cruce  \
230   AV. GRAL. PAZ Y MACHAIN      GRAL PAZ  PAZ, GRAL. AV.   True   
583  NUEVA YORK Y ALTA GRACIA         CALLE      NUEVA YORK   True   

        dirección normalizada  comuna                               xy (caba)  \
230  PAZ, GRAL. AV. y MACHAIN      12  Point (97098.48468623 109019.96106626)   
583  NUEVA YORK y ALTA GRACIA      11  Point (94080.62190808 102083.62453795)   

            pos x         pos y     participantes victima      acusado  
230  -58.49491054  -34.54795581  AUTO-OBJETO FIJO    AUTO  OBJETO FIJO  
583  -58.52783814  -34.61047001  PEATON_MOTO-MOTO      SD         MOTO

### Variables Geográficas
Verificamos los datos geográficos ya que son parte importante para un análisis de accidentes de tránsito; así que traemos a observación los datos de las columnas 'xy_(caba)', 'pos_x', y 'pos_y', que contienen respectivamente datos de: geocodificación plana, longitud con separador punto y latitud con separador punto. 

Vemos que podemos extraer coordenadas de la columna 'xy_(caba)', así que se utiliza una función para dicho fin:

In [38]:
# Esta función utiliza una expresión regular (re.findall) para buscar todas las coincidencias de números decimales (que tienen un punto como separador decimal) en el texto ingresado. 
# Estas coincidencias se almacenan en la lista coordenadas.
# return float(coordenadas[0]), float(coordenadas[1]): Si se encontraron dos coordenadas, se convierten en números de punto flotante (float) y se devuelven como una tupla de dos valores.
# Luego, se aplica esta función a la columna 'XY (CABA)' de df_siniestros utilizando el método .map(). 
# Esto se hace para cada fila de la columna, y los resultados se almacenan en dos nuevas columnas, 'coord_x' y 'coord_y', utilizando zip(*...).

def extraer_coordenadas(texto):
    # Utilizamos una expresión regular para extraer las coordenadas
    coordenadas = re.findall(r'\d+\.\d+', texto)
    if len(coordenadas) == 2:
        return float(coordenadas[0]), float(coordenadas[1])
    else:
        return None, None

# Aplicamos la función a la columna 'xt (caba)'
dfHechos['coord_x'], dfHechos['coord_y'] = zip(*dfHechos['xy (caba)'].map(extraer_coordenadas))

# Filtrar los registros que no tienen coordenadas válidas
dfHechos = dfHechos[(dfHechos['coord_x'].notnull()) & (dfHechos['coord_y'].notnull())]

In [39]:
dfHechos[['id hecho', 'xy (caba)', 'coord_x', 'coord_y']]

id hecho                                xy (caba)        coord_x  \
0    2016-0001    Point (98896.78238426 93532.43437792)   98896.782384   
1    2016-0002    Point (95832.05571093 95505.41641999)   95832.055711   
2    2016-0003   Point (106684.29090040 99706.57687843)  106684.290900   
3    2016-0004    Point (99840.65224780 94269.16534422)   99840.652248   
4    2016-0005  Point (106980.32827929 100752.16915795)  106980.328279   
..         ...                                      ...            ...   
691  2021-0093   Point (102728.60090138 98186.24929177)  102728.600901   
692  2021-0094    Point (99624.29795829 97569.69801131)   99624.297958   
693  2021-0095   Point (99116.45492358 101045.23284826)   99116.454924   
694  2021-0096    Point (99324.54463985 97676.26932409)   99324.544640   
695  2021-0097  Point (107664.16647795 104708.63962087)  107664.166478   

           coord_y  
0     93532.434378  
1     95505.416420  
2     99706.576878  
3     94269.165344  
4    100752.169158  
..             ...  
691   98186.249292  
692   97569.698011  
693  101045.232848  
694   97676.269324  
695  104708.639621  

[682 rows x 4 columns]

In [40]:
dfHechos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 682 entries, 0 to 695
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   id hecho               682 non-null    object        
 1   n victimas             682 non-null    int64         
 2   fecha                  682 non-null    datetime64[ns]
 3   año                    682 non-null    int64         
 4   mes                    682 non-null    int64         
 5   día                    682 non-null    int64         
 6   hora                   682 non-null    object        
 7   hora entera            682 non-null    object        
 8   lugar del hecho        682 non-null    object        
 9   tipo de calle          682 non-null    object        
 10  calle                  682 non-null    object        
 11  cruce                  682 non-null    bool          
 12  dirección normalizada  682 non-null    object        
 13  comuna    

Para facilitar el análisis posterior, agregamos la columna 'day name'; esta columna se usará para identificar que relación tiene la ocurrencia de los siniestro en el transcurso de la semana. 

In [41]:
# Transformamos a datetime
dfHechos['day name'] = pd.to_datetime(dfHechos['fecha'])
# Extraemos el número del día de la semana con el atributo day_of_week
dfHechos['day name'] = dfHechos['day name'].dt.day_of_week
# Reemplazamos por los nombres del día
dfHechos['day name'] = dfHechos['day name'].replace({
    0: 'Lunes',
    1: 'Martes',
    2: 'Miércoles',
    3: 'Jueves',
    4: 'Viernes',
    5: 'Sábado',
    6: 'Domingo'
})

In [42]:
dfHechos.head()

id hecho  n victimas      fecha   año  mes  día      hora hora entera  \
0  2016-0001           1 2016-01-01  2016    1    1  04:00:00           4   
1  2016-0002           1 2016-01-02  2016    1    2  01:15:00           1   
2  2016-0003           1 2016-01-03  2016    1    3  07:00:00           7   
3  2016-0004           1 2016-01-10  2016    1   10  00:00:00           0   
4  2016-0005           1 2016-01-21  2016    1   21  05:20:00           5   

                             lugar del hecho tipo de calle  ... comuna  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...      8   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...      9   
2                         AV ENTRE RIOS 2034       AVENIDA  ...      1   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...      8   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...      1   

                                 xy (caba)         pos x         pos y  \
0    Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1    Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2   Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3    Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4  Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   

    participantes victima    acusado        coord_x        coord_y day name  
0       MOTO-AUTO    MOTO       AUTO   98896.782384   93532.434378  Viernes  
1  AUTO-PASAJEROS    AUTO  PASAJEROS   95832.055711   95505.416420   Sábado  
2       MOTO-AUTO    MOTO       AUTO  106684.290900   99706.576878  Domingo  
3         MOTO-SD    MOTO         SD   99840.652248   94269.165344  Domingo  
4  MOTO-PASAJEROS    MOTO  PASAJEROS  106980.328279  100752.169158   Jueves  

[5 rows x 23 columns]

### Resumen descriptivo de la tabla **'HECHOS'**
Con este resumen descriptivo se puede ver de manera general los datos que obtuvimos finalmente en el dataframe 'dfHechos'. 

In [43]:
dfSummary(dfHechos)

### **VÍCTIMAS**

In [44]:
dfVictimas

ID_hecho      FECHA  AAAA  MM  DD                   ROL VICTIMA  \
0    2016-0001 2016-01-01  2016   1   1             CONDUCTOR    MOTO   
1    2016-0002 2016-01-02  2016   1   2             CONDUCTOR    AUTO   
2    2016-0003 2016-01-03  2016   1   3             CONDUCTOR    MOTO   
3    2016-0004 2016-01-10  2016   1  10             CONDUCTOR    MOTO   
4    2016-0005 2016-01-21  2016   1  21             CONDUCTOR    MOTO   
..         ...        ...   ...  ..  ..                   ...     ...   
712  2021-0092 2021-12-12  2021  12  12                PEATON  PEATON   
713  2021-0093 2021-12-13  2021  12  13  PASAJERO_ACOMPAÑANTE    MOTO   
714  2021-0094 2021-12-20  2021  12  20  PASAJERO_ACOMPAÑANTE    MOTO   
715  2021-0095 2021-12-30  2021  12  30             CONDUCTOR    MOTO   
716  2021-0096 2021-12-15  2021  12  15             CONDUCTOR    AUTO   

          SEXO EDAD  FECHA_FALLECIMIENTO  
0    MASCULINO   19  2016-01-01 00:00:00  
1    MASCULINO   70  2016-01-02 00:00:00  
2    MASCULINO   30  2016-01-03 00:00:00  
3    MASCULINO   18                   SD  
4    MASCULINO   29  2016-02-01 00:00:00  
..         ...  ...                  ...  
712   FEMENINO   50  2021-12-12 00:00:00  
713   FEMENINO   18  2021-12-18 00:00:00  
714   FEMENINO   43  2021-12-20 00:00:00  
715  MASCULINO   27  2022-01-02 00:00:00  
716  MASCULINO   60  2021-12-20 00:00:00  

[717 rows x 10 columns]

In [45]:
dfVictimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_hecho             717 non-null    object        
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64         
 3   MM                   717 non-null    int64         
 4   DD                   717 non-null    int64         
 5   ROL                  717 non-null    object        
 6   VICTIMA              717 non-null    object        
 7   SEXO                 717 non-null    object        
 8   EDAD                 717 non-null    object        
 9   FECHA_FALLECIMIENTO  717 non-null    object        
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB


Empezamos a ver la información general de como viene conformada la tabla 'víctimas', y podemos ver que tiene un total de 717 filas x 10 columnas.
Procedemos a normalizar los nombres de las columnas para mejor manipulación:

In [46]:
# Cambiamos el nombre de las columnas a minúsculas 
dfVictimas.columns = [x.lower() for x in dfVictimas.columns]
# Cambiamos los guiones por espacios
dfVictimas.columns = dfVictimas.columns.str.replace('_', ' ')

In [47]:
dfVictimas = dfVictimas.rename(columns={'aaaa':'año',
                                        'mm':'mes',
                                        'dd':'día',})

In [48]:
dfVictimas.columns

Index(['id hecho', 'fecha', 'año', 'mes', 'día', 'rol', 'victima', 'sexo',
       'edad', 'fecha fallecimiento'],
      dtype='object')

## Revisión de Datos (Víctimas)
### Datos Nulos

In [49]:
DataType(dfVictimas)

name                                          data_type  \
0             id hecho                                    [<class 'str'>]   
1                fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
2                  año                                    [<class 'int'>]   
3                  mes                                    [<class 'int'>]   
4                  día                                    [<class 'int'>]   
5                  rol                                    [<class 'str'>]   
6              victima                                    [<class 'str'>]   
7                 sexo                                    [<class 'str'>]   
8                 edad                     [<class 'int'>, <class 'str'>]   
9  fecha fallecimiento       [<class 'datetime.datetime'>, <class 'str'>]   

   not_null_%  null_%  null  
0       100.0     0.0     0  
1       100.0     0.0     0  
2       100.0     0.0     0  
3       100.0     0.0     0  
4       100.0     0.0     0  
5       100.0     0.0     0  
6       100.0     0.0     0  
7       100.0     0.0     0  
8       100.0     0.0     0  
9       100.0     0.0     0

Podemos ver que la tabla 'victimas' no tiene valores nulos; así que procedemos con los:
### Datos Duplicados

In [50]:
dfVictimas[dfVictimas.duplicated()]

Empty DataFrame
Columns: [id hecho, fecha, año, mes, día, rol, victima, sexo, edad, fecha fallecimiento]
Index: []

In [51]:
dfVictimas[dfVictimas.duplicated(subset=['id hecho'], keep=False)]

id hecho      fecha   año  mes  día                   rol victima  \
29   2016-0041 2016-03-29  2016    3   29             CONDUCTOR    MOTO   
30   2016-0041 2016-03-29  2016    3   29  PASAJERO_ACOMPAÑANTE    MOTO   
98   2016-0126 2016-09-18  2016    9   18             CONDUCTOR    AUTO   
99   2016-0126 2016-09-18  2016    9   18  PASAJERO_ACOMPAÑANTE    AUTO   
163  2017-0026 2017-02-26  2017    2   26  PASAJERO_ACOMPAÑANTE    AUTO   
164  2017-0026 2017-02-26  2017    2   26             CONDUCTOR    AUTO   
173  2017-0035 2017-03-23  2017    3   23             CONDUCTOR    AUTO   
174  2017-0035 2017-03-23  2017    3   23  PASAJERO_ACOMPAÑANTE    AUTO   
175  2017-0035 2017-03-23  2017    3   23  PASAJERO_ACOMPAÑANTE    AUTO   
176  2017-0036 2017-03-29  2017    3   29  PASAJERO_ACOMPAÑANTE    MOTO   
177  2017-0036 2017-03-29  2017    3   29             CONDUCTOR    MOTO   
186  2017-0050 2017-04-28  2017    4   28             CONDUCTOR    MOTO   
187  2017-0050 2017-04-28  2017    4   28  PASAJERO_ACOMPAÑANTE    MOTO   
237  2017-0108 2017-09-02  2017    9    2  PASAJERO_ACOMPAÑANTE    AUTO   
238  2017-0108 2017-09-02  2017    9    2  PASAJERO_ACOMPAÑANTE    AUTO   
242  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE    AUTO   
243  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE    AUTO   
253  2017-0126 2017-10-14  2017   10   14  PASAJERO_ACOMPAÑANTE    AUTO   
254  2017-0126 2017-10-14  2017   10   14             CONDUCTOR    AUTO   
277  2017-0153 2017-12-11  2017   12   11  PASAJERO_ACOMPAÑANTE    MOTO   
278  2017-0153 2017-12-11  2017   12   11             CONDUCTOR    MOTO   
300  2018-0015 2018-02-06  2018    2    6             CONDUCTOR    MOTO   
301  2018-0015 2018-02-06  2018    2    6  PASAJERO_ACOMPAÑANTE    MOTO   
312  2018-0026 2018-03-09  2018    3    9             CONDUCTOR   MOVIL   
313  2018-0026 2018-03-09  2018    3    9  PASAJERO_ACOMPAÑANTE   MOVIL   
325  2018-0038 2018-04-20  2018    4   20                PEATON  PEATON   
326  2018-0038 2018-04-20  2018    4   20                PEATON  PEATON   
373  2018-0085 2018-08-03  2018    8    3  PASAJERO_ACOMPAÑANTE    MOTO   
374  2018-0085 2018-08-03  2018    8    3             CONDUCTOR    MOTO   
387  2018-0098 2018-09-09  2018    9    9             CONDUCTOR    AUTO   
388  2018-0098 2018-09-09  2018    9    9  PASAJERO_ACOMPAÑANTE    AUTO   
418  2018-0128 2018-11-25  2018   11   25  PASAJERO_ACOMPAÑANTE    AUTO   
419  2018-0128 2018-11-25  2018   11   25  PASAJERO_ACOMPAÑANTE    AUTO   
444  2019-0010 2019-02-02  2019    2    2                PEATON  PEATON   
445  2019-0010 2019-02-02  2019    2    2                PEATON  PEATON   
576  2020-0038 2020-08-30  2020    8   30             CONDUCTOR    AUTO   
577  2020-0038 2020-08-30  2020    8   30             CONDUCTOR    AUTO   
602  2020-0063 2020-12-05  2020   12    5                PEATON  PEATON   
603  2020-0063 2020-12-05  2020   12    5  PASAJERO_ACOMPAÑANTE    MOTO   
616  2020-0077 2020-12-25  2020   12   25             CONDUCTOR    MOTO   
617  2020-0077 2020-12-25  2020   12   25  PASAJERO_ACOMPAÑANTE    MOTO   

          sexo edad  fecha fallecimiento  
29   MASCULINO   54  2016-03-29 00:00:00  
30   MASCULINO   SD  2016-03-30 00:00:00  
98   MASCULINO   37                   SD  
99   MASCULINO   60                   SD  
163   FEMENINO   23  2017-02-26 00:00:00  
164  MASCULINO   19  2017-02-26 00:00:00  
173  MASCULINO   28  2017-03-23 00:00:00  
174  MASCULINO   32  2017-03-23 00:00:00  
175  MASCULINO   30  2017-03-23 00:00:00  
176   FEMENINO   SD  2017-03-29 00:00:00  
177  MASCULINO   20  2017-03-29 00:00:00  
186  MASCULINO   46  2017-04-28 00:00:00  
187  MASCULINO   16  2017-04-28 00:00:00  
237  MASCULINO   17  2017-09-02 00:00:00  
238  MASCULINO   10  2017-09-02 00:00:00  
242  MASCULINO    1                   SD  
243  MASCULINO   SD  2017-09-13 00:00:00  
253  MASCULINO   39                   SD  
254  MASCULINO   36  2017-10-14 00:00:

In [52]:
dfVictimas[dfVictimas.duplicated(subset=['id hecho'], keep=False)].value_counts().sum()

41

Estos datos duplicados representan el hecho de que existen múltiples víctimas por hecho, por lo que se conservan las filas.

### Tipos de Datos

In [53]:
DataType(dfVictimas)

name                                          data_type  \
0             id hecho                                    [<class 'str'>]   
1                fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
2                  año                                    [<class 'int'>]   
3                  mes                                    [<class 'int'>]   
4                  día                                    [<class 'int'>]   
5                  rol                                    [<class 'str'>]   
6              victima                                    [<class 'str'>]   
7                 sexo                                    [<class 'str'>]   
8                 edad                     [<class 'int'>, <class 'str'>]   
9  fecha fallecimiento       [<class 'datetime.datetime'>, <class 'str'>]   

   not_null_%  null_%  null  
0       100.0     0.0     0  
1       100.0     0.0     0  
2       100.0     0.0     0  
3       100.0     0.0     0  
4       100.0     0.0     0  
5       100.0     0.0     0  
6       100.0     0.0     0  
7       100.0     0.0     0  
8       100.0     0.0     0  
9       100.0     0.0     0

Empezamos revisando la columna 'edad', ya que dice que tiene datos de tipo int pero también str, así que revisamos los de tipo str:

In [54]:
dfVictimas['edad'].apply(type).value_counts()

edad
<class 'int'>    664
<class 'str'>     53
Name: count, dtype: int64

In [55]:
dfVictimas[dfVictimas['edad'].apply(type) == str]

id hecho      fecha   año  mes  día                   rol    victima  \
30   2016-0041 2016-03-29  2016    3   29  PASAJERO_ACOMPAÑANTE       MOTO   
33   2016-0045 2016-04-11  2016    4   11             CONDUCTOR       MOTO   
35   2016-0048 2016-04-15  2016    4   15                PEATON     PEATON   
36   2016-0049 2016-04-17  2016    4   17                    SD         SD   
39   2016-0052 2016-04-20  2016    4   20                    SD       MOTO   
55   2016-0077 2016-06-13  2016    6   13                PEATON     PEATON   
63   2016-0085 2016-06-29  2016    6   29                    SD       MOTO   
72   2016-0096 2016-07-25  2016    7   25             CONDUCTOR       MOTO   
89   2016-0115 2016-09-02  2016    9    2                    SD         SD   
93   2016-0119 2016-09-04  2016    9    4  PASAJERO_ACOMPAÑANTE         SD   
108  2016-0136 2016-10-25  2016   10   25             CONDUCTOR       MOTO   
119  2016-0148 2016-11-16  2016   11   16             CONDUCTOR       MOTO   
121  2016-0151 2016-11-18  2016   11   18                PEATON     PEATON   
138  2016-0171 2016-12-25  2016   12   25             CONDUCTOR       MOTO   
141  2016-0174 2016-12-27  2016   12   27                    SD         SD   
142  2016-0175 2016-12-27  2016   12   27                PEATON     PEATON   
165  2017-0027 2017-02-26  2017    2   26                PEATON     PEATON   
176  2017-0036 2017-03-29  2017    3   29  PASAJERO_ACOMPAÑANTE       MOTO   
182  2017-0042 2017-04-10  2017    4   10             CONDUCTOR       MOTO   
225  2017-0093 2017-07-25  2017    7   25                PEATON     PEATON   
243  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE       AUTO   
275  2017-0151 2017-12-04  2017   12    4                PEATON     PEATON   
277  2017-0153 2017-12-11  2017   12   11  PASAJERO_ACOMPAÑANTE       MOTO   
299  2018-0014 2018-01-31  2018    1   31                PEATON     PEATON   
328  2018-0040 2018-04-27  2018    4   27                PEATON     PEATON   
359  2018-0071 2018-07-10  2018    7   10             CONDUCTOR       MOTO   
367  2018-0079 2018-07-23  2018    7   23                PEATON     PEATON   
371  2018-0083 2018-08-02  2018    8    2             CONDUCTOR       MOTO   
377  2018-0088 2018-08-17  2018    8   17             CONDUCTOR       MOTO   
391  2018-0101 2018-09-21  2018    9   21             CONDUCTOR       AUTO   
421  2018-0130 2018-12-03  2018   12    3             CONDUCTOR       MOTO   
444  2019-0010 2019-02-02  2019    2    2                PEATON     PEATON   
446  2019-0011 2019-02-10  2019    2   10                PEATON     PEATON   
454  2019-0019 2019-03-06  2019    3    6             CONDUCTOR       MOTO   
457  2019-0022 2019-03-15  2019    3   15  PASAJERO_ACOMPAÑANTE       AUTO   
461  2019-0026 2019-03-28  2019    3   28                PEATON     PEATON   
463  2019-0028 2019-04-06  2019    4    6                PEATON     PEATON   
469  2019-0034 2019-04-21  2019    4   21             CONDUCTOR       MOTO   
479  2019-0043 2019-05-21  2019    5   21              CICLISTA  BICICLETA   
498  2019-0063 2019-08-04  2019    8    4  PASAJERO_ACOMPAÑANTE       MOTO   
506  2019-0071 2019-08-27  2019    8   27                PEATON     PEATON   
529  2019-0094 2019-11-18  2019   11   18  PASAJERO_ACOMPAÑANTE       MOTO   
530  2019-0095 2019-11-20  2019   11   20             CONDUCTOR       MOTO   
548  2020-0010 2020-02-08  2020    2    8             CONDUCTOR       MOTO   
552  2020-0014 2020-02-27  2020    2   27             CONDUCTOR       MOTO   
555  2020-0017 2020-03-05  2020    3    5                PEATON     PEATON   
563  2020-0025 2020-05-12  2020    5   12                PEATON     PEATON   
572  2020-0034 2020-08-02  2020    8    2                PEATON     PEATON   
579  2020-0040 2020-09-12  2020    9   12             CONDUCTOR       AUTO   
631  2021-0012 2021-01-29  2021    1   29                PEATON     PEATON   
639  2021-0020 2021-02-21  2

Como podemos ver, los datos de tipo str que están en la columna 'edad' representan cerca del 7.4% de los datos, siendo estos los que tienen imputado 'SD' porque no se conoció la edad de la víctima. Pero a pesar de eso, se mantienen estos datos en el dataframe, ya que proporcionan información sobre la cantidad de víctimas mortales de los hechos, así que transformaremos estos datos de tal manera que podamos hacer análisis sin problemas más adelante. 

In [56]:
# Cambiamos la columna 'edad' a tipo int
dfVictimas['edad'] = pd.to_numeric(dfVictimas['edad'], errors='coerce')
dfVictimas['edad'] = dfVictimas['edad'].astype('Int64')

In [57]:
# Reemplazamos los datos que son 'SD' o vacíos por NaN
dfVictimas['edad'] = dfVictimas['edad'].replace([' ', 'SD'], np.nan)

In [58]:
dfVictimas['edad'] = dfVictimas['edad'].fillna(0.0)

In [59]:
# Verificamos los cambios
dfVictimas['edad'].unique()

<IntegerArray>
[19, 70, 30, 18, 29, 22, 16, 59, 65, 34, 41, 50, 38, 21, 52, 36, 20, 54,  0,
 56, 24, 78, 79, 26, 57, 37, 58, 23, 60, 42, 53, 51, 40, 87, 76, 75, 35, 80,
 43, 45, 67, 27, 55, 49, 81, 25, 33, 46, 83, 39, 28,  7, 48,  4, 82, 32, 17,
 47, 61, 10, 95, 73, 84, 66, 85,  1, 15, 13, 77, 44, 31, 62, 74, 71, 11, 86,
 69, 72, 12, 63, 92, 68, 91, 64,  5, 88]
Length: 86, dtype: Int64

Ahora revisaremos la columna 'fecha fallecimiento' que también contiene datos de tipo str:

In [60]:
dfVictimas['fecha fallecimiento'].apply(type).value_counts()

fecha fallecimiento
<class 'datetime.datetime'>    648
<class 'str'>                   69
Name: count, dtype: int64

In [61]:
dfVictimas[dfVictimas['fecha fallecimiento'].apply(type) == str]

id hecho      fecha   año  mes  día                   rol victima  \
3    2016-0004 2016-01-10  2016    1   10             CONDUCTOR    MOTO   
16   2016-0022 2016-02-21  2016    2   21  PASAJERO_ACOMPAÑANTE    MOTO   
19   2016-0027 2016-02-28  2016    2   28  PASAJERO_ACOMPAÑANTE    AUTO   
22   2016-0031 2016-03-08  2016    3    8             CONDUCTOR    MOTO   
33   2016-0045 2016-04-11  2016    4   11             CONDUCTOR    MOTO   
..         ...        ...   ...  ...  ...                   ...     ...   
242  2017-0112 2017-09-10  2017    9   10  PASAJERO_ACOMPAÑANTE    AUTO   
246  2017-0115 2017-09-19  2017    9   19             CONDUCTOR    MOTO   
253  2017-0126 2017-10-14  2017   10   14  PASAJERO_ACOMPAÑANTE    AUTO   
280  2017-0155 2017-12-12  2017   12   12                    SD      SD   
454  2019-0019 2019-03-06  2019    3    6             CONDUCTOR    MOTO   

          sexo  edad fecha fallecimiento  
3    MASCULINO    18                  SD  
16   MASCULINO    41                  SD  
19   MASCULINO    34                  SD  
22   MASCULINO    21                  SD  
33   MASCULINO     0                  SD  
..         ...   ...                 ...  
242  MASCULINO     1                  SD  
246  MASCULINO    34                  SD  
253  MASCULINO    39                  SD  
280  MASCULINO    77                  SD  
454  MASCULINO     0          26/03/2019  

[69 rows x 10 columns]

Vemos que sucede algo similar a lo de la columna 'edad', pues los datos exactos no se conocieron, pero sigue siendo información importante para este análisis así que conservaremos las filas. 

También se puede observar que hay una fila (fila 454) con una fecha en formato str, así que revisamos:

In [62]:
dfVictimas[(dfVictimas['fecha fallecimiento'].apply(type) == str) & (dfVictimas['fecha fallecimiento'] != 'SD')]

id hecho      fecha   año  mes  día        rol victima       sexo  edad  \
454  2019-0019 2019-03-06  2019    3    6  CONDUCTOR    MOTO  MASCULINO     0   

    fecha fallecimiento  
454          26/03/2019

Convertimos la columna 'fecha fallecimiento' a formato datatime excepto los que tiene 'SD':

In [63]:
dfVictimas['fecha fallecimiento'] = pd.to_datetime(dfVictimas['fecha fallecimiento'], errors='coerce').dt.date.fillna('SD')

In [64]:
# Verificamos los cambios realizados
dfVictimas['fecha fallecimiento'].apply(type).value_counts()

fecha fallecimiento
<class 'datetime.date'>    649
<class 'str'>               68
Name: count, dtype: int64

In [65]:
dfVictimas[(dfVictimas['fecha fallecimiento'].apply(type) == str) & (dfVictimas['fecha fallecimiento'] != 'SD')]

Empty DataFrame
Columns: [id hecho, fecha, año, mes, día, rol, victima, sexo, edad, fecha fallecimiento]
Index: []

Ahora crearemos un rango etario basado en la columna 'edad'; esto con el fin de segmentar las edades para efectos de facitilar el análisis posterior

In [66]:
# Para segmentar los datos de la columna 'edad' utilizamos la función 'cut', que se utiliza para agrupar datos númericos en rangos específicos. 
# Primero definimos los bins y las etiquetas 
bins = [0, 20, 40, 60, 80, 100]
labels = ['Menor de 20', 'Entre 21 y 40', 'Entre 41 y 60', 'Entre 61 y 80', 'Mayor de 80']
# Utilizamos la función 'cut' para agrupar los datos de la columna 'edad' en la nueva columna 'rango etario'
dfVictimas['rango etario'] = pd.cut(dfVictimas['edad'], bins=bins, labels=labels, right=False)
dfVictimas['rango etario'].head()

0      Menor de 20
1    Entre 61 y 80
2    Entre 21 y 40
3      Menor de 20
4    Entre 21 y 40
Name: rango etario, dtype: category
Categories (5, object): ['Menor de 20' < 'Entre 21 y 40' < 'Entre 41 y 60' < 'Entre 61 y 80' < 'Mayor de 80']

In [67]:
dfVictimas.head()

id hecho      fecha   año  mes  día        rol victima       sexo  edad  \
0  2016-0001 2016-01-01  2016    1    1  CONDUCTOR    MOTO  MASCULINO    19   
1  2016-0002 2016-01-02  2016    1    2  CONDUCTOR    AUTO  MASCULINO    70   
2  2016-0003 2016-01-03  2016    1    3  CONDUCTOR    MOTO  MASCULINO    30   
3  2016-0004 2016-01-10  2016    1   10  CONDUCTOR    MOTO  MASCULINO    18   
4  2016-0005 2016-01-21  2016    1   21  CONDUCTOR    MOTO  MASCULINO    29   

  fecha fallecimiento   rango etario  
0          2016-01-01    Menor de 20  
1          2016-01-02  Entre 61 y 80  
2          2016-01-03  Entre 21 y 40  
3                  SD    Menor de 20  
4          2016-02-01  Entre 21 y 40

### Variables 
Seguidamente vamos a verificar que los datos de la columna 'victima' pertenezcan a las categorias mencionadas en el diccionario de datos:

In [68]:
dfVictimas['victima'].unique()

array(['MOTO', 'AUTO', 'PEATON', 'SD', 'CARGAS', 'BICICLETA', 'PASAJEROS',
       'MOVIL'], dtype=object)

Vemos que no hay anomalía alguna con las categorías de la columna 'victima' en el dfVictimas.

### Resumen descriptivo de la tabla **'VÍCTIMAS'**

In [69]:
dfSummary(dfVictimas)

Ahora procedemos a guardar los dataframes en formato CSV:

In [70]:
dfHechos.to_csv('homicidios_hechos.csv', encoding='utf-8', index=False)
dfVictimas.to_csv('homicidios_victimas.csv', encoding='utf-8', index=False)

## Preparación de los Datasets para el Dashborad
Para poder hacer nuestro dashboard con toda la información de ambos dataframes, tenemos que unificarlos en un solo dataset; esto lo hacemos con la función merge que sirve para combinar dos o más dataframes en base a columnas comunes. 



In [71]:
dfHomicidios = pd.merge(dfHechos,dfVictimas[['id hecho', 'rol', 'sexo', 'edad', 'fecha fallecimiento']], how='right', on='id hecho')
dfHomicidios.head()

id hecho  n victimas      fecha     año  mes   día      hora hora entera  \
0  2016-0001         1.0 2016-01-01  2016.0  1.0   1.0  04:00:00           4   
1  2016-0002         1.0 2016-01-02  2016.0  1.0   2.0  01:15:00           1   
2  2016-0003         1.0 2016-01-03  2016.0  1.0   3.0  07:00:00           7   
3  2016-0004         1.0 2016-01-10  2016.0  1.0  10.0  00:00:00           0   
4  2016-0005         1.0 2016-01-21  2016.0  1.0  21.0  05:20:00           5   

                             lugar del hecho tipo de calle  ...  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...   
2                         AV ENTRE RIOS 2034       AVENIDA  ...   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...   

    participantes victima    acusado        coord_x        coord_y day name  \
0       MOTO-AUTO    MOTO       AUTO   98896.782384   93532.434378  Viernes   
1  AUTO-PASAJEROS    AUTO  PASAJEROS   95832.055711   95505.416420   Sábado   
2       MOTO-AUTO    MOTO       AUTO  106684.290900   99706.576878  Domingo   
3         MOTO-SD    MOTO         SD   99840.652248   94269.165344  Domingo   
4  MOTO-PASAJEROS    MOTO  PASAJEROS  106980.328279  100752.169158   Jueves   

         rol       sexo edad fecha fallecimiento  
0  CONDUCTOR  MASCULINO   19          2016-01-01  
1  CONDUCTOR  MASCULINO   70          2016-01-02  
2  CONDUCTOR  MASCULINO   30          2016-01-03  
3  CONDUCTOR  MASCULINO   18                  SD  
4  CONDUCTOR  MASCULINO   29          2016-02-01  

[5 rows x 27 columns]

In [72]:
DataType(dfHomicidios)

name                                          data_type  \
0                id hecho                                    [<class 'str'>]   
1              n victimas                                  [<class 'float'>]   
2                   fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                     año                                  [<class 'float'>]   
4                     mes                                  [<class 'float'>]   
5                     día                                  [<class 'float'>]   
6                    hora  [<class 'datetime.time'>, <class 'float'>, <cl...   
7             hora entera    [<class 'int'>, <class 'float'>, <class 'str'>]   
8         lugar del hecho                   [<class 'str'>, <class 'float'>]   
9           tipo de calle                   [<class 'str'>, <class 'float'>]   
10                  calle                   [<class 'str'>, <class 'float'>]   
11                  cruce                  [<class 'bool'>, <class 'float'>]   
12  dirección normalizada                   [<class 'str'>, <class 'float'>]   
13                 comuna                                  [<class 'float'>]   
14              xy (caba)                   [<class 'str'>, <class 'float'>]   
15                  pos x                   [<class 'str'>, <class 'float'>]   
16                  pos y                   [<class 'str'>, <class 'float'>]   
17          participantes                   [<class 'str'>, <class 'float'>]   
18                victima                   [<class 'str'>, <class 'float'>]   
19                acusado                   [<class 'str'>, <class 'float'>]   
20                coord_x                                  [<class 'float'>]   
21                coord_y                                  [<class 'float'>]   
22               day name                   [<class 'str'>, <class 'float'>]   
23                    rol                                    [<class 'str'>]   
24                   sexo                                    [<class 'str'>]   
25                   edad                                    [<class 'int'>]   
26    fecha fallecimiento           [<class 'datetime.date'>, <class 'str'>]   

    not_null_%  null_%  null  
0       100.00    0.00     0  
1        97.91    2.09    15  
2        97.91    2.09    15  
3        97.91    2.09    15  
4        97.91    2.09    15  
5        97.91    2.09    15  
6        97.91    2.09    15  
7        97.91    2.09    15  
8        97.91    2.09    15  
9        97.91    2.09    15  
10       97.91    2.09    15  
11       97.91    2.09    15  
12       97.91    2.09    15  
13       97.91    2.09    15  
14       97.91    2.09    15  
15       97.91    2.09    15  
16       97.91    2.09    15  
17       97.91    2.09    15  
18       97.91    2.09    15  
19       97.91    2.09    15  
20       97.91    2.09    15  
21       97.91    2.09    15  
22       97.91    2.09    15  
23      100.00    0.00     0  
24      100.00    0.00     0  
25      100.00    0.00     0  
26      100.00    0.00     0

In [73]:
# Eliminamos valores nulos 
dfHomicidios = dfHomicidios.dropna()

In [74]:
DataType(dfHomicidios)

name                                          data_type  \
0                id hecho                                    [<class 'str'>]   
1              n victimas                                  [<class 'float'>]   
2                   fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                     año                                  [<class 'float'>]   
4                     mes                                  [<class 'float'>]   
5                     día                                  [<class 'float'>]   
6                    hora           [<class 'datetime.time'>, <class 'str'>]   
7             hora entera                     [<class 'int'>, <class 'str'>]   
8         lugar del hecho                                    [<class 'str'>]   
9           tipo de calle                                    [<class 'str'>]   
10                  calle                                    [<class 'str'>]   
11                  cruce                                   [<class 'bool'>]   
12  dirección normalizada                                    [<class 'str'>]   
13                 comuna                                  [<class 'float'>]   
14              xy (caba)                                    [<class 'str'>]   
15                  pos x                                    [<class 'str'>]   
16                  pos y                                    [<class 'str'>]   
17          participantes                                    [<class 'str'>]   
18                victima                                    [<class 'str'>]   
19                acusado                                    [<class 'str'>]   
20                coord_x                                  [<class 'float'>]   
21                coord_y                                  [<class 'float'>]   
22               day name                                    [<class 'str'>]   
23                    rol                                    [<class 'str'>]   
24                   sexo                                    [<class 'str'>]   
25                   edad                                    [<class 'int'>]   
26    fecha fallecimiento           [<class 'datetime.date'>, <class 'str'>]   

    not_null_%  null_%  null  
0        100.0     0.0     0  
1        100.0     0.0     0  
2        100.0     0.0     0  
3        100.0     0.0     0  
4        100.0     0.0     0  
5        100.0     0.0     0  
6        100.0     0.0     0  
7        100.0     0.0     0  
8        100.0     0.0     0  
9        100.0     0.0     0  
10       100.0     0.0     0  
11       100.0     0.0     0  
12       100.0     0.0     0  
13       100.0     0.0     0  
14       100.0     0.0     0  
15       100.0     0.0     0  
16       100.0     0.0     0  
17       100.0     0.0     0  
18       100.0     0.0     0  
19       100.0     0.0     0  
20       100.0     0.0     0  
21       100.0     0.0     0  
22       100.0     0.0     0  
23       100.0     0.0     0  
24       100.0     0.0     0  
25       100.0     0.0     0  
26       100.0     0.0     0

In [75]:
# Ajustamos el tipo de dato de las columnas
dfHomicidios['n victimas'] = dfHomicidios['n victimas'].fillna(0.0)
dfHomicidios['n victimas'] = dfHomicidios['n victimas'].astype("Int64")

In [76]:
# Verificamos 'n victimas'
dfHomicidios['n victimas'].unique()

<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64

In [77]:
dfHomicidios['año'] = dfHomicidios['año'].astype("Int64")
dfHomicidios['año'].unique()

<IntegerArray>
[2016, 2017, 2018, 2019, 2020, 2021]
Length: 6, dtype: Int64

In [78]:
dfHomicidios['mes'] = dfHomicidios['mes'].astype("Int64")
dfHomicidios['mes'].unique()

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Length: 12, dtype: Int64

In [79]:
dfHomicidios['día'] = dfHomicidios['día'].astype("Int64")
dfHomicidios['día'].unique()

<IntegerArray>
[ 1,  2,  3, 10, 21, 24, 29,  8, 14, 15, 17, 28,  4, 12, 13, 19, 23, 30, 31,
 11, 20, 22, 25, 26, 16, 18, 27,  7,  9,  5,  6]
Length: 31, dtype: Int64

In [80]:
dfHomicidios['comuna'] = dfHomicidios['comuna'].astype("Int64")
dfHomicidios['comuna'].unique()

<IntegerArray>
[8, 9, 1, 11, 15, 4, 7, 12, 3, 13, 14, 10, 6, 2, 5]
Length: 15, dtype: Int64

In [81]:
dfHomicidios['hora'].apply(type).value_counts()

hora
<class 'datetime.time'>    701
<class 'str'>                1
Name: count, dtype: int64

In [82]:
# Filtramos los datos de la columna 'hora' que estan como str
dfHomicidios[dfHomicidios['hora'].apply(type) == str]['hora'].unique()

array(['SD'], dtype=object)

In [83]:
# Vamos a llenar el dato que aparece como 'SD' con la media de la columna 'hora'
# Para esto creamos la función que saca el promedio:
meanHora = pd.to_datetime(
    dfHomicidios['hora'],
    format = '%H:%M:%S',
    errors = 'coerce'
).dropna().mean()

# Luego reemplazamos los 'SD' por el promedio
dfHomicidios['hora'] = dfHomicidios['hora'].replace({'SD':meanHora.time()})


In [84]:
# Verificamos
dfHomicidios['hora'].apply(type).value_counts()

hora
<class 'datetime.time'>    702
Name: count, dtype: int64

In [85]:
# Hacemos lo mismo con la columna 'hora entera'
dfHomicidios['hora entera'].apply(type).value_counts()

hora entera
<class 'int'>    701
<class 'str'>      1
Name: count, dtype: int64

In [86]:
# Convertimos la columna 'hora entera' a numérico, convirtiendo los string en nulos
dfHomicidios['hora entera'] = pd.to_numeric(dfHomicidios['hora entera'], errors = 'coerce')

# Obtenemos la media de la columna 'hh'
meanHoraEntera = dfHomicidios['hora entera'].dropna().mean()

# Llenamos los datos nulos generados por la media
dfHomicidios['hora entera'].fillna(meanHoraEntera, inplace=True)

In [87]:
# Verificamos los tipos de datos 
DataType(dfHomicidios)

name                                          data_type  \
0                id hecho                                    [<class 'str'>]   
1              n victimas                                    [<class 'int'>]   
2                   fecha  [<class 'pandas._libs.tslibs.timestamps.Timest...   
3                     año                                    [<class 'int'>]   
4                     mes                                    [<class 'int'>]   
5                     día                                    [<class 'int'>]   
6                    hora                          [<class 'datetime.time'>]   
7             hora entera                                  [<class 'float'>]   
8         lugar del hecho                                    [<class 'str'>]   
9           tipo de calle                                    [<class 'str'>]   
10                  calle                                    [<class 'str'>]   
11                  cruce                                   [<class 'bool'>]   
12  dirección normalizada                                    [<class 'str'>]   
13                 comuna                                    [<class 'int'>]   
14              xy (caba)                                    [<class 'str'>]   
15                  pos x                                    [<class 'str'>]   
16                  pos y                                    [<class 'str'>]   
17          participantes                                    [<class 'str'>]   
18                victima                                    [<class 'str'>]   
19                acusado                                    [<class 'str'>]   
20                coord_x                                  [<class 'float'>]   
21                coord_y                                  [<class 'float'>]   
22               day name                                    [<class 'str'>]   
23                    rol                                    [<class 'str'>]   
24                   sexo                                    [<class 'str'>]   
25                   edad                                    [<class 'int'>]   
26    fecha fallecimiento           [<class 'datetime.date'>, <class 'str'>]   

    not_null_%  null_%  null  
0        100.0     0.0     0  
1        100.0     0.0     0  
2        100.0     0.0     0  
3        100.0     0.0     0  
4        100.0     0.0     0  
5        100.0     0.0     0  
6        100.0     0.0     0  
7        100.0     0.0     0  
8        100.0     0.0     0  
9        100.0     0.0     0  
10       100.0     0.0     0  
11       100.0     0.0     0  
12       100.0     0.0     0  
13       100.0     0.0     0  
14       100.0     0.0     0  
15       100.0     0.0     0  
16       100.0     0.0     0  
17       100.0     0.0     0  
18       100.0     0.0     0  
19       100.0     0.0     0  
20       100.0     0.0     0  
21       100.0     0.0     0  
22       100.0     0.0     0  
23       100.0     0.0     0  
24       100.0     0.0     0  
25       100.0     0.0     0  
26       100.0     0.0     0

In [88]:
dfHomicidios

id hecho  n victimas      fecha   año  mes  día      hora  hora entera  \
0    2016-0001           1 2016-01-01  2016    1    1  04:00:00          4.0   
1    2016-0002           1 2016-01-02  2016    1    2  01:15:00          1.0   
2    2016-0003           1 2016-01-03  2016    1    3  07:00:00          7.0   
3    2016-0004           1 2016-01-10  2016    1   10  00:00:00          0.0   
4    2016-0005           1 2016-01-21  2016    1   21  05:20:00          5.0   
..         ...         ...        ...   ...  ...  ...       ...          ...   
712  2021-0092           1 2021-12-12  2021   12   12  06:20:00          6.0   
713  2021-0093           1 2021-12-13  2021   12   13  17:10:00         17.0   
714  2021-0094           1 2021-12-20  2021   12   20  01:10:00          1.0   
715  2021-0095           1 2021-12-30  2021   12   30  00:43:00          0.0   
716  2021-0096           1 2021-12-15  2021   12   15  10:30:00         10.0   

                               lugar del hecho tipo de calle  ...  \
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...   
1            AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...   
2                           AV ENTRE RIOS 2034       AVENIDA  ...   
3        AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...   
4    AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...   
..                                         ...           ...  ...   
712             AV. RIVADAVIA Y AV. PUEYRREDON       AVENIDA  ...   
713                          AV. RIESTRA Y MOM       AVENIDA  ...   
714                    AU DELLEPIANE Y LACARRA     AUTOPISTA  ...   
715                        AV. GAONA Y TERRADA       AVENIDA  ...   
716                         AV. EVA PERON 4071       AVENIDA  ...   

      participantes victima    acusado        coord_x        coord_y  \
0         MOTO-AUTO    MOTO       AUTO   98896.782384   93532.434378   
1    AUTO-PASAJEROS    AUTO  PASAJEROS   95832.055711   95505.416420   
2         MOTO-AUTO    MOTO       AUTO  106684.290900   99706.576878   
3           MOTO-SD    MOTO         SD   99840.652248   94269.165344   
4    MOTO-PASAJEROS    MOTO  PASAJEROS  106980.328279  100752.169158   
..              ...     ...        ...            ...            ...   
712     PEATON-AUTO  PEATON       AUTO  105258.353686  102122.932314   
713       MOTO-AUTO    MOTO       AUTO  102728.600901   98186.249292   
714       MOTO-AUTO    MOTO       AUTO   99624.297958   97569.698011   
715     MOTO-CARGAS    MOTO     CARGAS   99116.454924  101045.232848   
716     AUTO-CARGAS    AUTO     CARGAS   99324.544640   97676.269324   

      day name                   rol       sexo edad fecha fallecimiento  
0      Viernes             CONDUCTOR  MASCULINO   19          2016-01-01  
1       Sábado             CONDUCTOR  MASCULINO   70          2016-01-02  
2      Domingo             CONDUCTOR  MASCULINO   30          2016-01-03  
3      Domingo             CONDUCTOR  MASCULINO   18                  SD  
4       Jueves             CONDUCTOR  MASCULINO   29          2016-02-01  
..         ...                   ...        ...  ...                 ...  
712    Domingo                PEATON   FEMENINO   50          2021-12-12  
713      Lunes  PASAJERO_ACOMPAÑANTE   FEMENINO   18          2021-12-18  
714      Lunes  PASAJERO_ACOMPAÑANTE   FEMENINO   43          2021-12-20  
715     Jueves             CONDUCTOR  MASCULINO   27          2022-01-02  
716  Miércoles             CONDUCTOR  MASCULINO   60          2021-12-20  

[702 rows x 27 columns]

### Resumen descriptivo de la tabla **'HOMICIDIOS'**

In [89]:
dfSummary(dfHomicidios)

In [90]:
# Guardamos el dataframe en formato CSV para mejor manipulación
dfHomicidios.to_csv('homicidios_merge.csv', encoding='utf-8', index=False)